services:
  chain-simulator:
    container_name: chain-simulator
    ports:
    - 8085:8085
    image: multiversx/chainsimulator:v1.11.3
    entrypoint: /bin/bash -c " sed -i 's|http://localhost:9200|http://elasticsearch:9200|g'
      ./config/node/config/external.toml && sed -i '11i\    { File = \"enableEpochs.toml\",
      Path = \"EnableEpochs.StakingV2EnableEpoch\", Value = 0},' ./config/nodeOverrideDefault.toml
      && ./start-with-services.sh -log-level *:INFO --rounds-per-epoch=5"
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://127.0.0.1:8085/simulator/observers
      interval: 10s
      timeout: 5s
      retries: 5
