# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: esdt.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nesdt.proto\x12\x15protoBuiltInFunctions\"\x8b\x01\n\x0e\x45SDigitalToken\x12\x0c\n\x04Type\x18\x01 \x01(\r\x12\r\n\x05Value\x18\x02 \x01(\x0c\x12\x12\n\nProperties\x18\x03 \x01(\x0c\x12\x36\n\rTokenMetaData\x18\x04 \x01(\x0b\x32\x1f.protoBuiltInFunctions.MetaData\x12\x10\n\x08Reserved\x18\x05 \x01(\x0c\"\x1a\n\tESDTRoles\x12\r\n\x05Roles\x18\x01 \x03(\x0c\"{\n\x08MetaData\x12\r\n\x05Nonce\x18\x01 \x01(\x04\x12\x0c\n\x04Name\x18\x02 \x01(\x0c\x12\x0f\n\x07\x43reator\x18\x03 \x01(\x0c\x12\x11\n\tRoyalties\x18\x04 \x01(\r\x12\x0c\n\x04Hash\x18\x05 \x01(\x0c\x12\x0c\n\x04URIs\x18\x06 \x03(\x0c\x12\x12\n\nAttributes\x18\x07 \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'esdt_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ESDIGITALTOKEN._serialized_start=38
  _ESDIGITALTOKEN._serialized_end=177
  _ESDTROLES._serialized_start=179
  _ESDTROLES._serialized_end=205
  _METADATA._serialized_start=207
  _METADATA._serialized_end=330
# @@protoc_insertion_point(module_scope)
