"""
Devnet test environment.

Provides access to MultiversX devnet (live test network) with:
- Pre-existing blockchain state
- Real network latency
- Natural block progression (~6s per block)
- Shared test environment (multiple users)
"""

import time
from typing import Optional
from multiversx_sdk import NetworkProviderConfig, ProxyNetworkProvider

from tests.environments.base_environment import TestEnvironment
from utils.utils_tx import NetworkProviders
from utils.logger import get_logger


logger = get_logger(__name__)


class DevnetEnvironment(TestEnvironment):
    """
    Devnet environment - live test network with pre-existing state.

    Features:
    - Connects to devnet-gateway.multiversx.com
    - Pre-deployed contracts available for testing
    - Real network conditions (latency, block time)
    - Shared environment (tests may interfere)

    Limitations:
    - NO time control (blocks generated by network validators)
    - NO state isolation (other users also testing)
    - Slower than chain simulator (~6s per block)
    - Requires internet connectivity

    Security Considerations:
    - Devnet is public, anyone can view transactions
    - Do NOT use mainnet PEMs or real assets
    - Test accounts may be drained by others
    - Nonce conflicts possible with concurrent users
    """

    def __init__(self,
                 proxy_url: str = "https://devnet-gateway.multiversx.com",
                 api_url: str = "https://devnet-api.multiversx.com"):
        """
        Initialize devnet environment.

        Args:
            proxy_url: Devnet gateway URL (default: official devnet)
            api_url: Devnet API URL (default: official devnet API)

        Example:
            >>> env = DevnetEnvironment()
            >>> env.setup()
        """
        self.proxy_url = proxy_url
        self.api_url = api_url
        self._proxy: Optional[ProxyNetworkProvider] = None
        self._network_providers: Optional[NetworkProviders] = None

        logger.info(f"Initialized DevnetEnvironment with proxy_url={proxy_url}")

    def setup(self) -> None:
        """
        Connect to devnet and verify network is responsive.

        Process:
        1. Initialize ProxyNetworkProvider
        2. Fetch network status to verify connectivity
        3. Log current epoch/block for debugging

        Raises:
            RuntimeError: If devnet is unreachable or returning errors
        """
        logger.info("Connecting to devnet...")

        self._proxy = ProxyNetworkProvider(self.proxy_url, None, NetworkProviderConfig("py-sdk-exchange"))
        assert self._proxy is not None, "Failed to initialize proxy"

        # Initialize network providers
        self._network_providers = NetworkProviders(self.api_url, self.proxy_url)

        # Verify connectivity
        try:
            status = self._proxy.get_network_status()
            logger.info(f"Connected to devnet: epoch {status.current_epoch}, block {status.highest_final_block_nonce}")
            logger.info(f"Chain ID: {self._proxy.get_network_config().chain_id}")
        except Exception as e:
            raise RuntimeError(f"Failed to connect to devnet: {e}")

    def teardown(self) -> None:
        """
        Cleanup devnet connection.

        Note: Devnet is a persistent network, so teardown is a no-op.
        We just clear the proxy reference.
        """
        logger.debug("Closing devnet connection")
        self._proxy = None
        self._network_providers = None

    def get_network_providers(self) -> NetworkProviders:
        """
        Get network providers for blockchain interactions.

        Returns:
            NetworkProviders: Network providers (API + Proxy) configured for devnet

        Raises:
            RuntimeError: If setup() was not called
        """
        if not self._network_providers:
            raise RuntimeError("Devnet not connected. Call setup() first.")
        return self._network_providers

    def supports_time_control(self) -> bool:
        """
        Check if this environment supports block/epoch manipulation.

        Returns:
            bool: Always False for devnet (live network)
        """
        return False

    def has_pre_existing_state(self) -> bool:
        """
        Check if environment has pre-deployed contracts.

        Returns:
            bool: Always True for devnet (persistent test network)
        """
        return True

    def advance_blocks(self, count: int) -> None:
        """
        Wait for natural block progression.

        IMPORTANT: This CANNOT generate blocks (live network).
        Instead, it sleeps for estimated time based on ~6s block time.

        Args:
            count: Number of blocks to wait for

        Warning:
            This is an approximation. Actual block times vary:
            - Cross-shard finality: up to 2 rounds (12s)
            - Network congestion may slow blocks
            - Use for waiting, NOT precise timing tests
        """
        wait_time = count * 6  # Approximate block time
        logger.debug(f"Waiting ~{wait_time}s for {count} block(s) on devnet")
        time.sleep(wait_time)

        # Log actual progress
        if self._proxy:
            status = self._proxy.get_network_status()
            logger.debug(f"Current block: {status.highest_final_block_nonce}, epoch: {status.current_epoch}")

    def advance_to_epoch(self, epoch: int) -> None:
        """
        Advance to specific epoch - NOT SUPPORTED on devnet.

        Args:
            epoch: Target epoch (ignored)

        Raises:
            NotImplementedError: Devnet epochs controlled by validators
        """
        raise NotImplementedError(
            "Cannot control epochs on devnet (live network). "
            "Epochs advance automatically every ~24 hours. "
            "Use chain simulator for epoch-dependent tests."
        )

    def get_current_epoch(self) -> int:
        """
        Get current blockchain epoch.

        Returns:
            int: Current epoch number on devnet

        Raises:
            RuntimeError: If devnet not connected
        """
        if not self._proxy:
            raise RuntimeError("Devnet not connected")

        return self._proxy.get_network_status().current_epoch

    def get_current_block(self) -> int:
        """
        Get current blockchain nonce (block number).

        Returns:
            int: Current block nonce on devnet

        Raises:
            RuntimeError: If devnet not connected
        """
        if not self._proxy:
            raise RuntimeError("Devnet not connected")

        return self._proxy.get_network_status().highest_final_block_nonce

    def wait_for_block_finality(self, blocks: int = 2) -> None:
        """
        Wait for cross-shard finality.

        MultiversX uses adaptive state sharding. Cross-shard transactions
        require additional rounds for finality. This helper waits for
        guaranteed finality.

        Args:
            blocks: Number of blocks to wait (default 2 for cross-shard)

        Recommendation:
        - Intra-shard: 1 block sufficient
        - Cross-shard: 2 blocks recommended
        - Critical operations: 3 blocks for safety
        """
        logger.debug(f"Waiting for finality ({blocks} blocks)")
        self.advance_blocks(blocks)
